sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t ubuntu-docker-sshd .
      - docker images
      - docker tag ubuntu-docker-sshd luismcplopes/ubuntu-docker-sshd

    - stage: test
      script: 
      - docker run --rm luismcplopes/ubuntu-docker-sshd cat /etc/os-*release
      - docker run --rm luismcplopes/ubuntu-docker-sshd cat /etc/apt/sources.list
  
  
